window.TOPIC_QUESTIONS = [
  {
    "id": "imported-005",
    "stem_en": "Which of the following test statistics is most appropriate for a hypothesis test  concerning the mean difference between two normally distributed populations?",
    "choices_en": [
      "A. t-statistic.",
      "B. F-statistic.",
      "C. Chi-square statistic."
    ],
    "answer": "A",
    "explanation_en": "Correct because for a lest of Mean Differences (Normally Distributed Populations, Unknown Population\nVariances), when we have data consisting of paired observations from samples generated by normally\ndistributed populations with unknown variances, a Ctest is based on f = (d — Uq))/Sy, with n — 1 degrees of\nfreedom, where nis the number of paired observations, d is the sample mean difference, and s, is the standard\nerror of a.",
    "los": "construct hypothesis tests and determine their statistical significance, the associated Type | and Type II errors, and power of the test given a significance level",
    "explanation_zh": ""
  },
  {
    "id": "imported-015",
    "stem_en": "To test whether a population's mean, μ, is greater than zero, the alternative  hypothesis should be formulated as:",
    "choices_en": [
      "A. μ≤0.",
      "B. μ≥0.",
      "C. μ>0."
    ],
    "answer": "C",
    "explanation_en": "Correct because despite the different ways to formulate hypotheses, we always conduct a test of the null\nhypothesis at the point of equality, 9 = G5. We may have a ‘suspected’ or ‘hoped for’ condition for which we want\nto find supportive evidence. In that case, we can formulate the alternative hypothesis as the statement that this\ncondition is true; the null hypothesis that we test is the statement that this condition is not true. Here, the\n“suspected” condition is that the population's mean is greater than zero (u = 0).",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": ""
  },
  {
    "id": "imported-034",
    "stem_en": "An analyst examines 30 paired monthly returns for two stock indexes. To  determine if the mean difference of the returns is zero, the number of degrees of  freedom of the t-test is.",
    "choices_en": [
      "A. 28.",
      "B. 29.",
      "C. 58."
    ],
    "answer": "B",
    "explanation_en": "Correct because the tstatistic for a paired comparisons test has n— 1 degrees of freedom, where nits the\nnumber of pairs of observations. When n = 30, the number of degrees of freedom is 30 — 1 = 29.",
    "los": "construct hypothesis tests and determine their statistical significance, the associated Type | and Type Il errors, and power of the test given a significance level",
    "explanation_zh": ""
  },
  {
    "id": "imported-036",
    "stem_en": "The probability of correctly rejecting a null hypothesis is best defined as the:",
    "choices_en": [
      "A. p-value.",
      "B. power of the test.",
      "C. level of significance."
    ],
    "answer": "B",
    "explanation_en": "Correct because the power of a test is the probability of Correct /y rejecting the null—that is, the probability of\nrejecting the null when it ts false.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": ""
  },
  {
    "id": "imported-064",
    "stem_en": "The probability of correctly rejecting a false null hypothesis is best described as  one minus the:",
    "choices_en": [
      "A. test statistic's p-value.",
      "B. probability of a Type I error.",
      "C. probability of a Type II error."
    ],
    "answer": "C",
    "explanation_en": "Correct because the power of a test is the probability of Correct ly rejecting the nullthat ts, the probability of\nrejecting the null when it ts false. Failing to reject the null hypothesis when it ts false is a Type Il error. So the\npower of the test is equal to one minus the probability of Type II error.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": ""
  },
  {
    "id": "imported-082",
    "stem_en": "An analyst performs a hypothesis test concerning the difference between the  mean returns of two portfolios, assuming normally distributed populations with  unknown but equal variances. If the analyst decides to change the hypothesized  difference in mean returns from 0% to 1%, which of the following will change?",
    "choices_en": [
      "A. The value of the test statistic.",
      "B. The degrees of freedom used in the test.",
      "C. The pooled estimate of the common population variance."
    ],
    "answer": "A",
    "explanation_en": "Correct because when the unknown population variances are equal, a -test based on independent random\nsamples is given by t= (X; — Xp — by + Yo)/(S,7/N; + §,*/N2)* where Su is a pooled estimator of the common\nVariance. Hence, a change in hypothesized difference yu, — p> will change the value of the test statistic.",
    "los": "ma construct hypothesis tests and determine their statistical significance, the associated Type | and Type Il errors, and power of the test given a significance level",
    "explanation_zh": ""
  },
  {
    "id": "imported-091",
    "stem_en": "In hypothesis testing, which of the following best describes a Type II error?",
    "choices_en": [
      "A. Rejecting a true null hypothesis.",
      "B. Rejecting a false null hypothesis.",
      "C. Failure to reject a false null hypothesis."
    ],
    "answer": "C",
    "explanation_en": "Correct because, when we make a decision in a hypothesis test, we run the risk of making either a Type l ora\nType Il error. These are mutually exclusive errors: If we mistakenly reject the null hypothesis, we can only be\nmaking a Type | error, if we mistakenly fail to reject the null, we can only be making a Type II error.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": ""
  }
];
