window.TOPIC_QUESTIONS = [
  {
    "id": "imported-005",
    "stem_en": "Which of the following test statistics is most appropriate for a hypothesis test  concerning the mean difference between two normally distributed populations?",
    "choices_en": [
      "A. t-statistic.",
      "B. F-statistic.",
      "C. Chi-square statistic."
    ],
    "answer": "A",
    "explanation_en": "Correct because for a lest of Mean Differences (Normally Distributed Populations, Unknown Population\nVariances), when we have data consisting of paired observations from samples generated by normally\ndistributed populations with unknown variances, a Ctest is based on f = (d — Uq))/Sy, with n — 1 degrees of\nfreedom, where nis the number of paired observations, d is the sample mean difference, and s, is the standard\nerror of a.",
    "los": "construct hypothesis tests and determine their statistical significance, the associated Type | and Type II errors, and power of the test given a significance level",
    "explanation_zh": "【知识点】t-test for Mean Differences (Paired Samples)。当两个正态分布总体的方差未知,且数据是配对观测(如同一批标的在两个时点的收益率)时,应使用配对样本 t 检验,统计量 t = (d̄ − μd0)/s_d̄,自由度为 n−1。F 统计量用于检验两个方差是否相等,卡方统计量用于检验单一总体方差,均不适用于均值差异检验,故答案为 A。"
  },
  {
    "id": "imported-015",
    "stem_en": "To test whether a population's mean, μ, is greater than zero, the alternative  hypothesis should be formulated as:",
    "choices_en": [
      "A. μ≤0.",
      "B. μ≥0.",
      "C. μ>0."
    ],
    "answer": "C",
    "explanation_en": "Correct because despite the different ways to formulate hypotheses, we always conduct a test of the null\nhypothesis at the point of equality, 9 = G5. We may have a ‘suspected’ or ‘hoped for’ condition for which we want\nto find supportive evidence. In that case, we can formulate the alternative hypothesis as the statement that this\ncondition is true; the null hypothesis that we test is the statement that this condition is not true. Here, the\n“suspected” condition is that the population's mean is greater than zero (u = 0).",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": "【知识点】alternative hypothesis (Ha) 与 null hypothesis (H0)。检验惯例是零假设 H0 永远取等号那一侧,备择假设 Ha 表达研究者怀疑或希望证明的方向。本题怀疑「总体均值大于0」,故应写 Ha: μ>0(对应 H0: μ≤0,检验时在 μ=0 处进行)。选项 A、B 把等号放进了备择假设,不符合「H0 取等号」的规则,故排除。"
  },
  {
    "id": "imported-034",
    "stem_en": "An analyst examines 30 paired monthly returns for two stock indexes. To  determine if the mean difference of the returns is zero, the number of degrees of  freedom of the t-test is.",
    "choices_en": [
      "A. 28.",
      "B. 29.",
      "C. 58."
    ],
    "answer": "B",
    "explanation_en": "Correct because the tstatistic for a paired comparisons test has n— 1 degrees of freedom, where nits the\nnumber of pairs of observations. When n = 30, the number of degrees of freedom is 30 — 1 = 29.",
    "los": "construct hypothesis tests and determine their statistical significance, the associated Type | and Type Il errors, and power of the test given a significance level",
    "explanation_zh": "【知识点】t-test for Mean Differences (Paired Samples) 的自由度。配对 t 检验的自由度 df = n−1,n 是「配对」的组数,而不是两组数据的总观测数。题目中两组指数各30个月度收益率两两配对,n=30,故 df = 30−1 = 29,选 B。选项 C 的58误用了两独立样本 t 检验的自由度公式 n1+n2−2(30+30−2=58),不适用于配对检验。"
  },
  {
    "id": "imported-036",
    "stem_en": "The probability of correctly rejecting a null hypothesis is best defined as the:",
    "choices_en": [
      "A. p-value.",
      "B. power of the test.",
      "C. level of significance."
    ],
    "answer": "B",
    "explanation_en": "Correct because the power of a test is the probability of Correct /y rejecting the null—that is, the probability of\nrejecting the null when it ts false.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": "【知识点】power of a test。检验功效被定义为「正确拒绝一个为假的零假设」的概率,恰好对应题干「correctly rejecting the null hypothesis」的描述。p-value 是零假设为真时观察到当前样本(或更极端结果)的概率;显著性水平是研究者能容忍的最大第一类错误概率,二者都不是本题定义,故答案为 B。"
  },
  {
    "id": "imported-064",
    "stem_en": "The probability of correctly rejecting a false null hypothesis is best described as  one minus the:",
    "choices_en": [
      "A. test statistic's p-value.",
      "B. probability of a Type I error.",
      "C. probability of a Type II error."
    ],
    "answer": "C",
    "explanation_en": "Correct because the power of a test is the probability of Correct ly rejecting the nullthat ts, the probability of\nrejecting the null when it ts false. Failing to reject the null hypothesis when it ts false is a Type Il error. So the\npower of the test is equal to one minus the probability of Type II error.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": "【知识点】power of a test = 1 − P(Type II error)。第二类错误(Type II error)是零假设为假却「未被拒绝」;检验功效(power)则是正确拒绝为假零假设的概率,二者互补。因此「正确拒绝一个为假的零假设」的概率 = 1 − P(第二类错误),选 C。选项 B 把 Type I 与 Type II 弄反了,Type I error 是零假设为真却被拒绝,与本题描述无关。"
  },
  {
    "id": "imported-082",
    "stem_en": "An analyst performs a hypothesis test concerning the difference between the  mean returns of two portfolios, assuming normally distributed populations with  unknown but equal variances. If the analyst decides to change the hypothesized  difference in mean returns from 0% to 1%, which of the following will change?",
    "choices_en": [
      "A. The value of the test statistic.",
      "B. The degrees of freedom used in the test.",
      "C. The pooled estimate of the common population variance."
    ],
    "answer": "A",
    "explanation_en": "Correct because when the unknown population variances are equal, a -test based on independent random\nsamples is given by t= (X; — Xp — by + Yo)/(S,7/N; + §,*/N2)* where Su is a pooled estimator of the common\nVariance. Hence, a change in hypothesized difference yu, — p> will change the value of the test statistic.",
    "los": "ma construct hypothesis tests and determine their statistical significance, the associated Type | and Type Il errors, and power of the test given a significance level",
    "explanation_zh": "【知识点】t-test for Mean Differences (Independent Samples, Equal Variances)。两独立样本、方差未知但相等时,t = [(X̄1−X̄2)−(μ1−μ2)]/√(Sp²/n1+Sp²/n2),其中联合方差 Sp² 只由两组样本自身的方差和样本量决定,自由度 df=n1+n2−2 也只取决于样本量,均与假设的均值差 μ1−μ2 无关。把假设差异从0%改为1%,只改变分子中的假设值,从而改变 t 统计量的取值,故答案为 A;B、C 均不受影响。"
  },
  {
    "id": "imported-093",
    "stem_en": "In hypothesis testing, which of the following best describes a Type II error?",
    "choices_en": [
      "A. Rejecting a true null hypothesis.",
      "B. Rejecting a false null hypothesis.",
      "C. Failure to reject a false null hypothesis."
    ],
    "answer": "C",
    "explanation_en": "Correct because, when we make a decision in a hypothesis test, we run the risk of making either a Type l ora\nType Il error. These are mutually exclusive errors: If we mistakenly reject the null hypothesis, we can only be\nmaking a Type | error, if we mistakenly fail to reject the null, we can only be making a Type II error.",
    "los": "explain hypothesis testing and its components, including statistical significance, Type | and Type Il errors, and the power of a test.",
    "explanation_zh": "【知识点】Type II error。第一类错误(Type I error)是拒绝了实际为真的 H0;第二类错误(Type II error)是「未能拒绝」实际为假的 H0,对应选项 C。两类错误互斥,不会同时发生。选项 A 描述的是 Type I error,选项 B 描述的其实是正确决策(拒绝了假的 H0,不是错误),均不符合 Type II error 的定义,故答案为 C。"
  }
];
