window.TOPIC_QUESTIONS = [
  {
    "id": "imported-007",
    "stem_en": "Which of the following statements is most accurate? Cryptocurrencies",
    "choices_en": [
      "A. exhibit low volatility.",
      "B. have no limits on the total amount of currency that may be issued.",
      "C. allow transactions between parties without the need for an intermediary."
    ],
    "answer": "C",
    "explanation_en": "Correct because a cryptocurrency, also known as a digital currency, operates as electronic currency and\nallows near-real-time transactions between parties without the need for an intermediary, such as a bank.",
    "los": "describe financial applications of distributed ledger technology",
    "explanation_zh": ""
  },
  {
    "id": "imported-011",
    "stem_en": "Which of the following statements is most accurate with respect to the  widespread adoption of algorithmic trading in financial markets?",
    "choices_en": [
      "A. The need for low-latency networks has grown.",
      "B. Markets have become less fragmented in terms of trading venues.",
      "C. Average trade size has increased as algorithmic trading is used to execute  large institutional orders."
    ],
    "answer": "A",
    "explanation_en": "Correct because algorithmic trading requires access to low-latency networks, and with the wide-spread\nadoption of algorithmic trading, the need for low-latency networks has grown. Low-latency systems—systems\nthat operate on networks that communicate high volumes of data with minimal delay (latency)—are essential for\nautomated trading applications that make decisions based on real-time prices and market events. In contrast,\nhigh-latency systems do not require access to real-time data and calculations. High-frequency trading is a form\nof algorithmic trading that makes use of vast quantities of granular financial data (tick data, for example) to\nautomatically place trades when certain conditions are met. Trades are executed on ultra-high-speed, low-\nlatency networks in fractions of a second.",
    "los": "describe applications of Big Data and Data Science to investment management",
    "explanation_zh": ""
  },
  {
    "id": "imported-012",
    "stem_en": "The failure of machine learning models to accurately predict outcomes can be the  result of:",
    "choices_en": [
      "A. overfitting, but not underfitting.",
      "B. underfitting, but not overfitting.",
      "C. either overfitting or underfitting"
    ],
    "answer": "C",
    "explanation_en": "Correct because an ML model that has been overfitted is not able to accurately predict outcomes using a\ndifferent dataset and may be too complex. Also, underfitted models will typically fail to fully discover patterns that\nunderlie the data and thus may not be able to accurately predict outcomes.",
    "los": "describe Big Data, artificial intelligence, and machine leaming",
    "explanation_zh": ""
  },
  {
    "id": "imported-014",
    "stem_en": "Which of the following is most likely an advantage of traditional financial  advisers over fully automated digital wealth managers?",
    "choices_en": [
      "A. Lower account minimums.",
      "B. Dividend reinvestment options.",
      "C. Solutions that better address the needs of complex portfolios."
    ],
    "answer": "C",
    "explanation_en": "Correct because as the complexity and size of an investor's portfolio grows, robo-advisers may not be able to\nsufficiently address the particular preferences and needs of the investor. In the case of extremely affluent\ninvestors who may own a greater number of asset types—including altemative investments (e.g., venture\ncapital, private equity, hedge funds, and real estate)—in addition to global stocks and bonds and have greater\ndemands for customization, the need for a team of human advisers, each with particular areas of investment or\nwealth-management expertise, ts likely to endure.",
    "los": "describe Big Data, artificial intelligence, and machine leaming",
    "explanation_zh": ""
  },
  {
    "id": "imported-022",
    "stem_en": "In its broadest sense, fintech is best described as:",
    "choices_en": [
      "A. the vast amount of data being generated by the financial services industry.",
      "B. the execution of investment strategies through computer-generated  algorithms.",
      "C. technological innovation in the design and delivery of financial services and  products."
    ],
    "answer": "C",
    "explanation_en": "Correct because in its broadest sense, the term hntech generally refers to technology-driven innovation\noccurring in the financial services industry. For the purposes of this reading, fintech refers to technological\ninnovation in the design and delivery of financial services and products. Note, however, that in common usage,\nfintech can also refer fo companies (often new, startup companies) involved in developing the new technologies\nand their applications, as well as the business sector that comprises such companies.",
    "los": "sa describe aspects of “fintech” that are directly relevant for the gathering and analyzing of financial data.",
    "explanation_zh": ""
  },
  {
    "id": "imported-029",
    "stem_en": "Which of the following is most likely used to detect sentiment shifts in an  analyst's commentary?",
    "choices_en": [
      "A. Tokenization.",
      "B. Data curation.",
      "C. Natural language processing."
    ],
    "answer": "C",
    "explanation_en": "Correct because NLP [natural language processing] may be used to monitor analyst commentary to aid\ninvestment decision making. Since analysts tend not to change their buy, hold, and sell recommendations for a\ncompany frequently, they may instead offer nuanced commentary without making a change in their investment\nrecommendation. NLP can, therefore, be used to detect, monitor, and tag shifts in sentiment, potentially ahead\nof an analyst's recommendation change.",
    "los": "describe applications of Big Data and Data Science to investment management",
    "explanation_zh": ""
  },
  {
    "id": "imported-077",
    "stem_en": "The process of representing ownership rights to physical assets on a distributed  ledger is referred to as:",
    "choices_en": [
      "A. tokenization.",
      "B. initial coin offering.",
      "C. consensus mechanism."
    ],
    "answer": "A",
    "explanation_en": "Correct because tokenization is the process of representing ownership rights to physical assets on a blockchain\nor distributed ledger.",
    "los": "# describe financial applications of distributed ledger technology",
    "explanation_zh": ""
  },
  {
    "id": "imported-079",
    "stem_en": "Which of the following statements about distributed ledger technology is most  accurate?",
    "choices_en": [
      "A. Bitcoin uses a permissioned network.",
      "B. Miners execute smart contracts in the blockchain.",
      "C. Tokenization can streamline the transfer of ownership of physical assets."
    ],
    "answer": "C",
    "explanation_en": "Correct because through tokenization, the process of representing ownership rights to physical assets on a\nblockchain or distributed ledger, distributed ledger technology (DLT) has the potential to streamline this process\nby creating a single, digital record of ownership with which to verify ownership title and authenticity, including all\nhistorical activity.",
    "los": "ma describe financial applications of distributed ledger technology",
    "explanation_zh": ""
  }
];
